negative_replies = [
    "I understand it can be frustrating. Can you provide more details?",
    "I'm sorry to hear that. How can I assist you further?",
    "I apologize if there was any inconvenience caused. Please let me know how I can help.",
    "I'm here to assist you. What specific issue are you facing?",
    "I'm sorry if things haven't been going well. Let's work together to resolve your concern.",
    "I can imagine it's tough for you. How can I make things better?",
    "I'm here to support you. Let's find a solution together.",
    "I'm sorry that you're feeling this way. Is there anything specific you'd like to discuss?",
    "I understand that it's challenging. Let's see what we can do to improve the situation.",
    "I'm sorry if my responses haven't been helpful. Please let me know how I can assist you better.",
    "I'm sorry, I wish I could change the situation for you.",
    "I understand your frustration. Let's see if we can find a solution together.",
    "I'm here to listen and help. What can I do to make things better?",
    "I'm sorry if I'm not meeting your expectations. Let me know how I can improve.",
    "I'm sorry for any inconvenience caused. How can I make it right?",
    "I understand how disappointing that can be. Let's work on finding a solution.",
    "I'm here to support you. Please let me know how I can assist you further.",
    "I'm sorry if my responses are not what you were hoping for. How can I do better?",
    "I'm sorry to hear that. Is there anything specific I can do to help?",
    "I'm here to help you through this. What can I do to make things easier?",
    "I apologize if I'm not meeting your needs. How can I improve?",
    "I'm sorry if I've let you down. Please let me know how I can make it right.",
    "I understand that this is frustrating for you. Let's find a way to resolve it.",
    "I'm sorry if my assistance hasn't been satisfactory. How can I assist you better?",
    "I apologize for any inconvenience caused. Let's work together to find a solution.",
    "I'm here to support you. Let's address the issue together.",
    "I'm sorry if my responses aren't helpful. Please provide more details so I can assist you better.",
    "I understand that you're upset. Let's figure out how to make things right.",
    "I apologize if my assistance has been lacking. Let's work on improving it.",
    "I'm sorry if I'm not meeting your expectations. How can I better assist you?",
    "I'm here to help. Please let me know what I can do to make things better for you.",
    "I'm sorry if my support hasn't been up to par. Let's work together to find a resolution.",
    "I'm sorry to hear that.",
    "That's really unfortunate.",
    "I understand how you feel.",
    "It's disheartening.",
    "I'm here for you.",
    "Sending virtual hugs.",
    "Stay strong.",
    "I wish things were different.",
    "I empathize with you.",
    "Take your time to heal.",
    "You're not alone.",
    "This too shall pass.",
    "I'm here to listen.",
    "Hang in there.",
    "It's okay to feel sad.",
    "Sending positive thoughts your way.",
    "Remember that tomorrow is a new day.",
    "You're stronger than you think.",
    "Sending support and love.",
    "Allow yourself to grieve.",
    "Sometimes life can be tough.",
    "I'm keeping you in my thoughts.",
    "Take care of yourself.",
    "I'm sorry you're going through this.",
    "Sending virtual comfort.",
    "You're not defined by your sadness.",
    "You have the strength to overcome.",
    "Don't hesitate to reach out for support.",
    "It's okay to not be okay.",
    "Sending you healing vibes."]

positive_replies = [
    "That's wonderful!",
    "Great job!",
    "You're doing fantastic!",
    "I'm so proud of you!",
    "Keep up the amazing work!",
    "You're making excellent progress!",
    "You have a heart of gold!",
    "You brighten up my day!",
    "You're a ray of sunshine!",
    "You're amazing just the way you are!",
    "I believe in you!",
    "You're capable of anything!",
    "You're an inspiration!",
    "You have a beautiful soul!",
    "You're a true superstar!",
    "You make the world a better place!",
    "Your efforts are appreciated!",
    "You're making a positive difference!",
    "You deserve all the happiness in the world!",
    "You're loved and cherished!",
    "You're a rockstar!",
    "You've got this!",
    "You're making great strides!",
    "You have a heart full of love!",
    "You light up the room with your smile!",
    "You bring joy to those around you!",
    "You have an incredible spirit!",
    "You're simply amazing!",
    "You're a source of inspiration for others!",
    "You're filled with boundless potential!",
    "You're an absolute delight!",
    "You have a heart of gold!",
    "You make every day brighter!",
    "You have a beautiful soul!",
    "You're a blessing in my life!",
    "You're an absolute treasure!",
    "You're a shining star!",
    "You're capable of achieving anything!",
    "You radiate love and positivity!",
    "You're a true gem!",
    "You're an incredible friend!",
    "You bring so much joy to my life!",
    "You're a beacon of light!",
    "You're a source of strength!",
    "You have a heart full of love and kindness!",
    "You're an extraordinary person!",
    "You make the world a better place just by being in it!",
    "You're a true inspiration to me!",
    "You have an indomitable spirit!",
    "You have a heart that's full of love and compassion!",
    "You're doing an amazing job!",
    "You're incredibly talented!",
    "You have so much to offer!",
    "You're making a positive impact on those around you!",
    "You have a heart of gold and a beautiful soul!",
    "You're a gift to the world!",
    "You're a true blessing in my life!",
    "You have the power to achieve your dreams!",
    "You're loved beyond measure!",
    "You have a smile that can brighten anyone's day!",
    "You're an incredible person inside and out!",
    "You're a true champion!",
    "You have a heart that's overflowing with love!",
    "You're a constant source of inspiration!",
    "You're making a difference in the world!",
    "You're deserving of all the love and happiness in the universe!",
    "You have a heart that's filled with compassion!",
    "You're an extraordinary individual!",
    "You have the power to create positive change!",
    "You're a source of light and positivity!",
    "You're destined for greatness!",
    "Amazing!",
    "You're doing great!",
    "Bravo!",
    "Outstanding!",
    "Superb!",
    "Terrific!",
    "Well played!",
    "Keep it up!",
    "You're on fire!",
    "Great job!",
    "Impressive work!",
    "You've got this!",
    "You're a star!",
    "That's incredible!",
    "Way to go!",
    "You're making fantastic progress!",
    "Excellent work!",
    "I'm impressed!",
    "Keep shining!",
    "You're nailing it!",
    "You're a champ!",
    "Fabulous!",
    "Well executed!",
    "You're acing it!",
    "You're on the right track!",
    "Well deserved!",
    "You're unstoppable!",
    "I'm proud of you!",
    "You're making it look easy!",
    "Keep up the amazing effort!",
]